spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: root
        url: jdbc:postgresql://localhost:5433/AppMoviles
        username: postgres
    jpa:
        database: postgresql
        generate-ddl: false
        hibernate:
            ddl-auto: update
        show-sql: true
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: https://securetoken.google.com/gener8-c323f
                    jwk-set-uri: https://www.googleapis.com/robot/v1/metadata/jwk/securetoken@system.gserviceaccount.com